name: Z-NODE Autobuild Σ

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew  :znode-app:assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Z-NODE-debug
          path: app/build/outputs/apk/debug/*.apk
